// ACTION TYPES
export const AUTHENTICATION_FETCHING = "AUTHENTICATION_FETCHING";
export const AUTHENTICATION_FULFILLED = "AUTHENTICATION_FULFILLED";
export const AUTHENTICATION_REJECTED = "AUTHENTICATION_REJECTED";
